// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ZkmQ1qmEwLIGY2qJmwafVSaMAdpXqz0',
    appId: '1:925477090329:web:4176b9a0d674a92767a688',
    messagingSenderId: '925477090329',
    projectId: 'fruit-hub-dad16',
    authDomain: 'fruit-hub-dad16.firebaseapp.com',
    storageBucket: 'fruit-hub-dad16.firebasestorage.app',
    measurementId: 'G-55CPV8YY88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSRMDWkoSt3maclAyzu37XL1X_QRFIgnI',
    appId: '1:925477090329:android:0703e56cfe083ff367a688',
    messagingSenderId: '925477090329',
    projectId: 'fruit-hub-dad16',
    storageBucket: 'fruit-hub-dad16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZl3WyIeiRsvuOyJIQ408A2WwChiYsr8',
    appId: '1:925477090329:ios:2ab50576a4e11eb767a688',
    messagingSenderId: '925477090329',
    projectId: 'fruit-hub-dad16',
    storageBucket: 'fruit-hub-dad16.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGZl3WyIeiRsvuOyJIQ408A2WwChiYsr8',
    appId: '1:925477090329:ios:2ab50576a4e11eb767a688',
    messagingSenderId: '925477090329',
    projectId: 'fruit-hub-dad16',
    storageBucket: 'fruit-hub-dad16.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ZkmQ1qmEwLIGY2qJmwafVSaMAdpXqz0',
    appId: '1:925477090329:web:d975b1f7391b2d8567a688',
    messagingSenderId: '925477090329',
    projectId: 'fruit-hub-dad16',
    authDomain: 'fruit-hub-dad16.firebaseapp.com',
    storageBucket: 'fruit-hub-dad16.firebasestorage.app',
    measurementId: 'G-YWLM9FLXYZ',
  );
}
